runtime: nodejs16
instance_class: B2
service: default

manual_scaling:
  instances: 3

handlers:

  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)
